// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuPE4Gd4dURJ7BvKdrVcSN72im0kjvVnk',
    appId: '1:459654112591:web:d4258fb5f8688590e8d13a',
    messagingSenderId: '459654112591',
    projectId: 'chat-app-5b63e',
    authDomain: 'chat-app-5b63e.firebaseapp.com',
    storageBucket: 'chat-app-5b63e.firebasestorage.app',
    measurementId: 'G-NRW3W32PW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdZYxVa2lMAhL7EM3ZEC8_rdU8JQPre2w',
    appId: '1:459654112591:android:025fdb8a45538cd1e8d13a',
    messagingSenderId: '459654112591',
    projectId: 'chat-app-5b63e',
    storageBucket: 'chat-app-5b63e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6FvuljCOKfigO-ruwIa7OdhJTHdkKPFg',
    appId: '1:459654112591:ios:dd1952f3cf42e8aee8d13a',
    messagingSenderId: '459654112591',
    projectId: 'chat-app-5b63e',
    storageBucket: 'chat-app-5b63e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6FvuljCOKfigO-ruwIa7OdhJTHdkKPFg',
    appId: '1:459654112591:ios:dd1952f3cf42e8aee8d13a',
    messagingSenderId: '459654112591',
    projectId: 'chat-app-5b63e',
    storageBucket: 'chat-app-5b63e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuPE4Gd4dURJ7BvKdrVcSN72im0kjvVnk',
    appId: '1:459654112591:web:e5b6dbcb9cd83bd9e8d13a',
    messagingSenderId: '459654112591',
    projectId: 'chat-app-5b63e',
    authDomain: 'chat-app-5b63e.firebaseapp.com',
    storageBucket: 'chat-app-5b63e.firebasestorage.app',
    measurementId: 'G-V59W554KH0',
  );
}
