// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk-PatGJo1VbaiBW4XVikWH26LXErBLQ8',
    appId: '1:885050409413:web:ca07fd87cf772d37338bac',
    messagingSenderId: '885050409413',
    projectId: 'chat-app-5676c',
    authDomain: 'chat-app-5676c.firebaseapp.com',
    storageBucket: 'chat-app-5676c.firebasestorage.app',
    measurementId: 'G-LK1YE8GW6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARkZTsi-SNvhbFhCJRQXbR36sCJ0urN-4',
    appId: '1:885050409413:android:2b94315efc7f7cf4338bac',
    messagingSenderId: '885050409413',
    projectId: 'chat-app-5676c',
    storageBucket: 'chat-app-5676c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOmqXeJn4pb8mLlg5UC505opyK-OXOxv8',
    appId: '1:885050409413:ios:c3f5e12e1f844592338bac',
    messagingSenderId: '885050409413',
    projectId: 'chat-app-5676c',
    storageBucket: 'chat-app-5676c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOmqXeJn4pb8mLlg5UC505opyK-OXOxv8',
    appId: '1:885050409413:ios:c3f5e12e1f844592338bac',
    messagingSenderId: '885050409413',
    projectId: 'chat-app-5676c',
    storageBucket: 'chat-app-5676c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk-PatGJo1VbaiBW4XVikWH26LXErBLQ8',
    appId: '1:885050409413:web:0788664e9740efce338bac',
    messagingSenderId: '885050409413',
    projectId: 'chat-app-5676c',
    authDomain: 'chat-app-5676c.firebaseapp.com',
    storageBucket: 'chat-app-5676c.firebasestorage.app',
    measurementId: 'G-D0YC5Q9VHS',
  );
}
